name: PR Workflow
run-name: PR by ${{ github.actor }}

on:
  push:
    branches:
      - "main"
  pull_request:
    branches:
      - "main"

env:
  GITHUB_ACTIONS: true

jobs:
  github-task-job:
    name: github-task-job
    runs-on: ubuntu-latest

    steps:
      - name: Show who triggered the workflow
        run: echo "Workflow triggered by user:${{ github.actor }}"

      - name: Show GITHUB_ACTIONS variable
        run: echo "GITHUB_ACTIONS = $GITHUB_ACTIONS"

      - name: Show branch and repository name
        run: |
          echo "Branch: ${{ github.head_ref }}"
          echo "Repository: ${{ github.repository }}"

      - name: Show event name
        run: echo "Event:${{ github.event_name }}"
