name: PR Workflow - ${{ github.actor }}

on:
  pull_request:

env:
  GITHUB_ACTIONS: true

jobs:
  github-task-job:
    name: github-task-job
    runs-on: ubuntu-latest
    steps:
      - name: Show GITHUB_ACTIONS variable
        run: echo "GITHUB_ACTIONS = $GITHUB_ACTIONS"

      - name: Show branch and repository name
        run: |
          echo "Branch: ${{ github.head_ref }}"
          echo "Repository: ${{ github.repository }}"

      - name: Show event name
        run: echo "Event:${{ github.event_name }}"
